language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest --cov utils_tabdata/ tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
